name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ "v1.23.3", "v1.22.5", "v1.21.2", "v1.20.7", "v1.19.7", "v1.18.8", "v1.17.5" ]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Kind cluster
        uses: helm/kind-action@v1.2.0
        with:
          cluster_name: operator-testing
          node_image: kindest/node:${{ matrix.node }}

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
